session_name: ts-retype
windows:
  - name: code
    panes:
      - cmd: node -v && nvim
  - name: git
  - name: dev
    layout: 2-col
    panes:
      - cmd: "npm -w vis run dev"
      - cmd: "npm -w clikit run watch"
      - cmd: "npm -w docs run dev"
      - cmd: "npm -w retype run watch"
      - cmd: "npm -w uikit run dev"
      - cmd: "npm -w scripts run watch"
